// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"hotgo/internal/dao/internal"
)

// aedLocationsDao is the data access object for the table aed_locations.
// You can define custom methods on it to extend its functionality as needed.
type aedLocationsDao struct {
	*internal.AedLocationsDao
}

var (
	// AedLocations is a globally accessible object for table aed_locations operations.
	AedLocations = aedLocationsDao{internal.NewAedLocationsDao()}
)

// Add your custom methods and functionality below.
