// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"hotgo/internal/dao/internal"
)

// userWxminiDao is the data access object for the table user_wxmini.
// You can define custom methods on it to extend its functionality as needed.
type userWxminiDao struct {
	*internal.UserWxminiDao
}

var (
	// UserWxmini is a globally accessible object for table user_wxmini operations.
	UserWxmini = userWxminiDao{internal.NewUserWxminiDao()}
)

// Add your custom methods and functionality below.
